# Generated by Django 4.1.7 on 2023-03-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=50)),
                ('Pprice', models.FloatField()),
                ('Pdescription', models.CharField(max_length=50)),
                ('Pbrand', models.CharField(max_length=20)),
                ('Pis_featured', models.BooleanField()),
                ('PCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
