# Generated by Django 4.1.7 on 2023-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
